export const ERROR_CODES = {
  BASE_DATA_MISSING: "BASE_DATA_MISSING",
  BLUE_DATA_MISSING: "BLUE_DATA_MISSING",
  GOLD_DATA_MISSING: "GOLD_DATA_MISSING",
  BREAKING_DATA_MISSING: "BREAKING_DATA_MISSING",
  INVALID_TARGET: "INVALID_TARGET",
  INVALID_CSV: "INVALID_CSV",
  DUPLICATE_DATA: "DUPLICATE_DATA",
  CSV_FILE_MISSING: "CSV_FILE_MISSING",
  GAME_DATA_NOT_DEPLOYED: "GAME_DATA_NOT_DEPLOYED",
  STORAGE_ERROR: "STORAGE_ERROR",
  IMPORT_REJECTED: "IMPORT_REJECTED",
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];

export const INCOMPLETE_CODES: ReadonlySet<string> = new Set<string>([
  ERROR_CODES.BASE_DATA_MISSING,
  ERROR_CODES.BLUE_DATA_MISSING,
  ERROR_CODES.GOLD_DATA_MISSING,
  ERROR_CODES.BREAKING_DATA_MISSING,
  ERROR_CODES.INVALID_TARGET,
]);
